// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRcQu4nsDNyASv8Z6CLFrim-_T3Q-66I',
    appId: '1:531713282766:web:c2a8fbb7e16271f061f69f', 
    messagingSenderId: '531713282766',
    projectId: 'stream-cart-mobile',
    authDomain: 'stream-cart-mobile.firebaseapp.com',
    storageBucket: 'stream-cart-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRcQu4nsDNyASv8Z6CLFrim-_T3Q-66I',
    appId: '1:531713282766:android:de3209a1702c41a761f69f',
    messagingSenderId: '531713282766',
    projectId: 'stream-cart-mobile',
    storageBucket: 'stream-cart-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASRcQu4nsDNyASv8Z6CLFrim-_T3Q-66I',
    appId: '1:531713282766:ios:your-ios-app-id', // Bạn cần tạo iOS app riêng
    messagingSenderId: '531713282766',
    projectId: 'stream-cart-mobile',
    storageBucket: 'stream-cart-mobile.firebasestorage.app',
    iosBundleId: 'com.example.stream_cart_mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASRcQu4nsDNyASv8Z6CLFrim-_T3Q-66I',
    appId: '1:531713282766:macos:your-macos-app-id',
    messagingSenderId: '531713282766',
    projectId: 'stream-cart-mobile',
    storageBucket: 'stream-cart-mobile.firebasestorage.app',
    iosBundleId: 'com.example.stream_cart_mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRcQu4nsDNyASv8Z6CLFrim-_T3Q-66I',
    appId: '1:531713282766:windows:your-windows-app-id',
    messagingSenderId: '531713282766',
    projectId: 'stream-cart-mobile',
    authDomain: 'stream-cart-mobile.firebaseapp.com',
    storageBucket: 'stream-cart-mobile.firebasestorage.app',
  );
}
